// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Battery
{
    public int BatteryId { get; set; }

    public int SellerId { get; set; }

    public string BatteryType { get; set; }

    public string Brand { get; set; }

    public string Capacity { get; set; }

    public string Voltage { get; set; }

    public string Condition { get; set; }

    public int? HealthPercentage { get; set; }

    public decimal Price { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual User Seller { get; set; }
}