// <auto-generated>Manually added to support battery order mapping.</auto-generated>
#nullable disable
using System;

namespace DAL.Models;

public partial class BatteryOrder
{
    public int OrderId { get; set; }

    public int BatteryId { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual Order Order { get; set; }
}

