// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Review
{
    public int ReviewId { get; set; }

    public int OrderId { get; set; }

    public int ReviewerId { get; set; }

    public int ReviewedUserId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime? CreatedDate { get; set; }

    public virtual Order Order { get; set; }

    public virtual User ReviewedUser { get; set; }

    public virtual User Reviewer { get; set; }
}