// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DAL.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public int SellerId { get; set; }

    public string Brand { get; set; }

    public string Model { get; set; }

    public int? Year { get; set; }

    public string BatteryCapacity { get; set; }

    public decimal Price { get; set; }

    public string Condition { get; set; }

    public int? Mileage { get; set; }

    public string Description { get; set; }

    public string ImageUrl { get; set; }

    public string Status { get; set; }

    public string ModerationNote { get; set; }

    public int? ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public DateTime? SubmittedDate { get; set; }

    public DateTime? PublishedDate { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual User Seller { get; set; }
    public virtual User ApprovedByNavigation { get; set; }
}