// <auto-generated>Manually added to support vehicle order mapping.</auto-generated>
#nullable disable
using System;

namespace DAL.Models;

public partial class VehicleOrder
{
    public int OrderId { get; set; }

    public int VehicleId { get; set; }

    public virtual Vehicle Vehicle { get; set; }

    public virtual Order Order { get; set; }
}

